AllCops:
  Exclude:
    - 'bin'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

# Overrides .rubocop-master.yml

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true

Rails/ActionFilter:
  EnforcedStyle: filter

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/SymbolProc:
  Enabled: false
