navigation_sections :
  - title : 'The Basics'
    pages :
      about :
      brand :
        title : 'Brand & Logo Guidelines'
  - title : 'Style'
    pages :
      typography :
      colour :
      icons :
  - title : 'Structure'
    pages :
      grid :
        title : 'Layout Grid'
      layout :
        title : 'Page Layout'
      hero :
        title : 'Hero Blocks'
      nav :
        title : 'Navigation'
  - title : 'Modules'
    pages :
      forms :
      cards :
      listings :
        title : 'Listings & Tables'
      alerts :
      buttons :

