navigation_sections :
  the-basics :
    title : 'The Basics'
    pages :
      about :
      brand :
        title : 'Brand & Logo Guidelines'
  style :
    pages :
      typography :
      colour :
      icons :
  structure :
    pages :
      grid :
        title : 'Layout Grid'
      layout :
        title : 'Page Layout'
      hero :
        title : 'Hero Blocks'
      nav :
        title : 'Navigation'
  modules :
    pages :
      forms :
      cards :
      listings :
        title : 'Listings & Tables'
      alerts :
      buttons :

example_pages :
  - menu :
      back_link : 'layout'
