name: button
title: Buttons
description: Button styles and that
variants:
  - classes: button
    content: Default
  - classes: button invert
    content: Inverted colours
  - classes: button subtle
    content: A subtle button
  - classes: button icon calendar
    content: Icon button
  - classes: button disabled
    content: Disabled button
  - classes: button square
    content: A squarer button
